Build is green on Vagrant. Will test on-device in morning.

diff --git a/files/rachelpios b/files/rachelpios
--- a/files/rachelpios
+++ b/files/rachelpios
@@ -1,84 +1,116 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-set -o errexit
-set -o nounset
+export DEBIAN_FRONTEND=noninteractive
+BASEDIR=/vagrant/files
 
-sudo apt-get update
-sudo rpi-update
-sudo apt-get -y dist-upgrade
+function assert() {
+    eval $(printf "%q " "$@")
+    RET=$?
+    if [ $RET != 0 ]; then
+        echo "Error while executing command: '$@'"
+        exit $RET
+    fi
+}
+
+function exists() {
+    if [[ -d $@ ]] || [[ -f $@ ]]; then
+        return 0;
+    fi
+    return 1;
+}
+
+function is_vagrant() {
+    return $(exists /etc/is_vagrant_vm)
+}
+
+assert sudo apt-get update
+if ! is_vagrant; then
+    assert sudo rpi-update
+fi
+assert sudo apt-get -y dist-upgrade
 
 
 #create wifi hotspot
-sudo apt-get -y install hostapd udhcpd
-sudo cp udhcpd.conf /etc/udhcpd.conf
-sudo cp udhcpd /etc/default/udhcpd
-sudo cp hostapd /etc/default/hostapd
-sudo cp interfaces /etc/network/interfaces
-sudo cp hostapd.conf /etc/hostapd/hostapd.conf
-sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
-sudo cp sysctl.conf /etc/sysctl.conf
-sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
-sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
-sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
-sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
+assert sudo apt-get -y install hostapd udhcpd
+assert sudo cp $BASEDIR/udhcpd.conf /etc/udhcpd.conf
+assert sudo cp $BASEDIR/udhcpd /etc/default/udhcpd
+assert sudo cp $BASEDIR/hostapd /etc/default/hostapd
+assert sudo cp $BASEDIR/interfaces /etc/network/interfaces
+assert sudo cp $BASEDIR/hostapd.conf /etc/hostapd/hostapd.conf
+assert sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
+assert sudo cp $BASEDIR/sysctl.conf /etc/sysctl.conf
+assert sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
+assert sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
+assert sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
+assert sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
 
 # this script should be able to run if the wifi is not present
 if ! ifconfig wlan0; then
     echo "Wifi device not present; skipping."
 else
-    sudo ifconfig wlan0 10.10.10.10
-    sudo service hostapd start
-    sudo service udhcpd start
-    sudo update-rc.d hostapd enable
-    sudo update-rc.d udhcpd enable
-    ./ifupdown.sh
+    assert sudo ifconfig wlan0 10.10.10.10
+    assert sudo service hostapd start
+    assert sudo service udhcpd start
+    assert sudo update-rc.d hostapd enable
+    assert sudo update-rc.d udhcpd enable
+    assert ./ifupdown.sh
 fi
 
 #install apache php mysql
-sudo apt-get -y install apache2 libapache2-mod-proxy-html libxml2-dev \
+assert echo mysql-server mysql-server/root_password password rachelpios | sudo debconf-set-selections
+assert echo mysql-server mysql-server/root_password_again password rachelpios | sudo debconf-set-selections
+assert sudo apt-get -y install apache2 libapache2-mod-proxy-html libxml2-dev \
      php5-common libapache2-mod-php5 php5-cgi php5 \
      mysql-server mysql-client php5-mysql
-sudo cp default /etc/apache2/sites-enabled/default
-sudo cp my.cnf /etc/mysql/my.cnf
-sudo a2enmod php5 proxy proxy_html rewrite # TODO: is this all that's needed?
-sudo service apache2 restart
+assert sudo cp $BASEDIR/default /etc/apache2/sites-enabled/default
+assert sudo cp $BASEDIR/my.cnf /etc/mysql/my.cnf
+assert sudo a2enmod php5 proxy proxy_html rewrite # TODO: is this all that's needed?
+assert sudo service apache2 restart
 
 #update hostname
-sudo cp hosts /etc/hosts
-sudo cp hostname /etc/hostname
-sudo /etc/init.d/hostname.sh
+assert sudo cp $BASEDIR/hosts /etc/hosts
+assert sudo cp $BASEDIR/hostname /etc/hostname
+if ! is_vagrant; then
+    assert sudo /etc/init.d/hostname.sh
+fi
 
 #install shamba share
-sudo apt-get -y install samba samba-common-bin
-sudo mkdir -p /var/www/local
-sudo chmod 777 /var/www/local
-sudo cp smb.conf /etc/samba/smb.conf
-# sudo cp dhcp.conf /etc/samba/dhcp.conf
-sudo cp gdbcommands /etc/samba/gdbcommands
+assert sudo apt-get -y install samba samba-common-bin
+assert sudo mkdir -p /var/www/local
+assert sudo chmod 777 /var/www/local
+assert sudo cp $BASEDIR/smb.conf /etc/samba/smb.conf
+# sudo cp $BASEDIR/dhcp.conf /etc/samba/dhcp.conf
+assert sudo cp $BASEDIR/gdbcommands /etc/samba/gdbcommands
 
 #install h5ai
 # TODO: figure out how to download package
 # mkdir -p /var/www/_h5ai
-# sudo cp default /etc/apache2/sites-available/default
+# sudo cp $BASEDIR/default /etc/apache2/sites-available/default
 # sudo apt-get -y install php5-gd ffmpeg zip imagemagick
 # sudo chmod 777 -R /var/www/_h5ai/cache/
 
 #install base www files
-sudo rm -f /var/www/index.html
-sudo cp -r www/* /var/www/
+assert sudo rm -f /var/www/index.html
+if ! is_vagrant; then 
+    assert sudo cp -r $BASEDIR/www/* /var/www/
+fi
 
 #put realtek drivers in place if needed
-sudo cp hostapd_RTL8188CUS /home/pi/hostapd_RTL
-sudo cp realtek.sh /home/pi/Desktop/realtek.sh
-sudo cp hostapd_realtek.conf /home/pi/hostapd_realtek.conf
+if ! is_vagrant; then
+    assert sudo cp $BASEDIR/hostapd_RTL8188CUS /home/pi/hostapd_RTL
+    assert sudo cp $BASEDIR/realtek.sh /home/pi/Desktop/realtek.sh
+    assert sudo cp $BASEDIR/hostapd_realtek.conf /home/pi/hostapd_realtek.conf
+fi
 
 #redo wifi enable for good measure
-if ifconfig wlan0; then
-    sudo ifconfig wlan0 10.10.10.10
-    sudo service hostapd start
-    sudo service udhcpd start
-    sudo update-rc.d hostapd enable
-    sudo update-rc.d udhcpd enable
+if ! is_vagrant; then
+    if ifconfig wlan0; then
+        sudo ifconfig wlan0 10.10.10.10
+        sudo service hostapd start
+        sudo service udhcpd start
+        sudo update-rc.d hostapd enable
+        sudo update-rc.d udhcpd enable
+    fi
 fi
 
 #install kiwix
